### ISSUE TITLE
missing license file in release package?

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4-python2#37]
http://stackoverflow.com/questions/28702871/licensing-for-python-antlr4/28703409#28703409

**Comment by ericvergnaud** [comment]
is there one available from the Java code base? I can't seem to find it.

**Comment by ericvergnaud** [comment]
Need your answer for the 4.5.2 release

**Comment by sharwell** [comment]
It's here: https://github.com/antlr/antlr4/blob/master/LICENSE.txt

**Comment by ericvergnaud** [comment]
added
