### ISSUE TITLE
Rewriting input stream not supported in ANTLR Python2 runtime?

### ISSUE THREAD

**Issue by RedTailedHawk** [antlr/antlr4-python2#40]
Originally mis-posted under antlr4 project:
    https://github.com/antlr/antlr4/issues/832

===
Is rewriting the input stream not supported in the ANTLR Python2 runtime? The ANTLR book discusses this technique in the Rewriting the Input Stream section, but I cannot find the TokenStreamRewriter class in the ANTLR Python 2 runtime.

I'm replacing a Python AST NodeTransformer with ANTLR, but I don't want to have to implement every listener method just to echo the text back out. TokenStreamRewriter is exactly what I need to transform part of the stream, but I can't find seem to find it.

Thanks for any help.

===

**Comment by sharwell** [comment]
Hi @RedTailedHawk,

As mentioned in the other issue, the only reason `TokenStreamRewriter` doesn't exist in this language target is no one has implemented it yet. By default this would be filed as a feature request for @ericvergnaud, but if it's a pressing issue for you another option is implementing this particular feature and submitting a pull request. (Make sure you tell post here if you are implementing it so we aren't duplicating work. :+1: )

**Comment by RedTailedHawk** [comment]
Thanks @sharwell, I don't think is a pressing issue for me anymore, so I'm continuing on with my ANTLR ramp-up.  I'll post here if I start implementing anything.

Thanks for the response.
