### ISSUE TITLE
Get context's children filtered by type

### ISSUE THREAD

**Issue by RedTailedHawk** [antlr/antlr4-python2#44]
I periodically need to iterate through a context's children filtered by a certain type.  For example:

```
def visitSomething(self, ctx):
    for child_ctx in [x for x in ctx.getChildren() if isinstance(x, myParser.some_particularContext)]:
```

Would it make sense to add an optional parameter to ParserRuleContext.getChildren to take a type?

```
def getChildren(self, ttype = None):
    if self.children is not None:
        for child in (self.children if ttype is None else [x for x in self.children if isinstance(x, ttype)]):
            yield child
```

Then I could change my consumer code to this:

```
def visitSomething(self, ctx):
    for child_ctx in ctx.getChildren(myParser.some_particularContext):
```

I can make the change in my branch and issue a pull request, but I wanted to ensure this makes sense.

Thanks.
-Larry

**Comment by ericvergnaud** [comment]
Hi,

nice idea
would make more sense to me to add an optional filter function parameter, which could then filter in/out tokens based on any kind of rule.

Eric

**Comment by RedTailedHawk** [comment]
I like that.

````
    def getChildren(self, predicate = None):
        if self.children is not None:
            for child in (self.children if predicate is None else [x for x in self.children if predicate(x)]):
                yield child
````

````
def visitSomething(self, ctx):
    for child_ctx in ctx.getChildren(lambda o: isinstance(o, myParser.some_particularContext)):
````

I'll commit on my branch and issue a pull request.

-Larry

**Comment by ericvergnaud** [comment]
Hi
still waiting for the PR

**Comment by RedTailedHawk** [comment]
Looks like it was pull request #45, and you merged on April 1st.  But honestly, I'm not really liking passing in an entire predicate.  In all of my code that used it, I passed in a lambda that checked the type with isinstance, and I ultimately added another method called getChildrenByType in my local branch and used that instead:

====
    def getChildrenByType(self, ttype):
        if self.children is not None:
            for child in self.children:
                if isinstance(child, ttype):
                    yield child
=====

Since ParserRuleContext.getChild() takes an optional ttype parameter, it would probably be more consistent to have getChildren() do that as well.

Not sure where to go from here.  I'm using my local copy with getChildrenByType, so I'm good at the moment.  But perhaps I should push getChildrenByType(), or we could change getChildren() to take a ttype parameter (and break compatibility and remove the predicate parameter).

Let me know what you think.

-Larry

**Comment by ericvergnaud** [comment]
you could add type as an optional named parameter to getChildren without removing predicate

**Comment by RedTailedHawk** [comment]
Right, but ttype may make sense as the second parameter, and predicate as the last.

    def getChildren(self, ttype = None, predicate = None)

That would break compatibility for anyone who is using getChildren() with predicate as the 2nd parameter.  But since it was my recent change, maybe nobody is using it yet.  :-)

So how about I change getChildren() as described above (with ttype 2nd, and predicate 3rd), and I'll push to my branch and issue a pull request.  I can probably get that done in the next hour or so.

**Comment by ericvergnaud** [comment]
I would expect people to use named parameters here, so the parameter order shouldn’t matter

your code would be as follows:

getChildren(ttype=whatever)

**Comment by RedTailedHawk** [comment]
I just submitted pull request #51:

Added ttype parameter to ParserRuleContext.getChildren() #51
