### ISSUE TITLE
self.children[i] if len(self.children)>=i else None

### ISSUE THREAD

**Issue by rljacobson** [antlr/antlr4-python2#46]
In ParserRuleContext.py we have the definition of getChild():

---snip---
def getChild(self, i, type = None):
    if type is None:
        return self.children[i] if len(self.children)>=i else None
---snip---

Surely the ">=" is meant to be strict, i.e.:
    return self.children[i] if len(self.children)>i else None

**Comment by ericvergnaud** [comment]
indeed, please sign the contributors agreement and submit a fix

**Comment by rljacobson** [comment]
Will do. Are you referring to the contributors agreement in the antlr4 repository (https://github.com/antlr/antlr4/blob/master/contributors.txt)? Or is there a separate one for antlr4-python2 specifically that I don't see?

**Comment by ericvergnaud** [comment]
It's the master one.

**Comment by rljacobson** [comment]
Pull request for contributor agreement (#850) and for the bug fix (#47) have been submitted. Cheers.
