### ISSUE TITLE
ETA for new release

### ISSUE THREAD

**Issue by eugene-bulkin** [antlr/antlr4-python2#48]
There have been some useful updates to this repo recently (namely, for me, the `removeErrorListener` method and similar ones), but no new release has been made since December. Will a v4.6 release (or v4.5.1) happen any time soon?

**Comment by ericvergnaud** [comment]
Hi,
there is no ETA. I was hoping to pull in some perf improvements, but the people who initially proposed them have vanished. I'll think about it.
Eric
