### ISSUE TITLE
Residual Java code left in generated python modules

### ISSUE THREAD

**Issue by g2graman** [antlr/antlr4-python2#49]
@parrt @ericvergnaud 
Running

    curl -O https://raw.githubusercontent.com/antlr/grammars-v4/master/ecmascript/ECMAScript.g4 cript.g4 -visitor

Retains java fragments, such as on line 731-765 of ECMAScriptLexer.py:
        
        // A flag indicating if the lexer should operate in strict mode.
        // When set to true, FutureReservedWords are tokenized, when false,
        // an octal literal can be tokenized.
        private boolean strictMode = true;

        // The most recently produced token.
        private Token lastToken = null;

        /**
         * Returns {@code true} iff the lexer operates in strict mode.
         *
         * @return {@code true} iff the lexer operates in strict mode.
         */
        public boolean getStrictMode() {
            return this.strictMode;
        }

        /**
         * Sets whether the lexer operates in strict mode or not.
         *
         * @param strictMode
         *         the flag indicating the lexer operates in strict mode or not.
         */
        public void setStrictMode(boolean strictMode) {
            this.strictMode = strictMode;
        }

        /**
         * Return the next token from the character stream and records this last
         * token in case it resides on the default channel. This recorded token
         * is used to determine when the lexer could possibly match a regex
         * literal.
         *
         * @return the next token from the character stream.
         */

And though this is okay for static environments that that only need to generate the parser/lexer once, if a build includes dynamically generating the parser/lexer (such as mine) then this becomes a problem.

The file, for the record, that I use to invoke the parser is a basic modification from the website:

    from antlr4 import *
    from ECMAScriptLexer import ECMAScriptLexer
    from ECMAScriptParser import ECMAScriptParser
    from ECMAScriptVisitor import ECMAScriptVisitor
    import sys
 
    def main(argv):
        input = FileStream(argv[1])
        lexer = ECMAScriptLexer(input)
        stream = CommonTokenStream(lexer)
        parser = ECMAScriptParser(stream)
        tree = parser.StartRule()
 
     if __name__ == '__main__':
        main(sys.argv)

**Comment by sharwell** [comment]
The grammar you refer to uses `@lexer::members` and `@parser::members` to insert code in a specific language. You'll have to do one of the following to use this grammar with the Python runtime:

1. Port the grammar to use Python code in those blocks
2. Rewrite the grammar to not use language-specific constructs (may not be possible)
3. Use the Java runtime

The `@members` named action was created specifically for this purpose. In addition, the grammar you referred to is not part of the Python runtime repository and not advertised as a grammar for use with the Python runtime, so this issue should probably be closed as "by-design".

**Comment by ericvergnaud** [comment]
Hi,
as mentioned by Sam, this is not a defect of the Python generator.
Eric

**Comment by DSblizzard** [comment]
"Port the grammar to use Python code in those blocks"
How to do it? I replaced java code with python code and receive following error:
Block starting  at line 38 offset 17 contains imbalanced {} or is missing a }
error(99): Python3.g4::: grammar Python3 has no rules

**Comment by ericvergnaud** [comment]
You must have left a typo

**Comment by DSblizzard** [comment]
What about this code and error:

NEWLINE
 : ( {atStartOfInput()}?   SPACES
   | ( '\r'? '\n' | '\r' ) SPACES?
   )
    
    if 1:
        lst = [1 for i in range(5)]
        pass
 ;

error(50): Python3.g4:738:7: syntax error: '1' came as a complete surprise to me
 while looking for lexer rule element
error(50): Python3.g4:739:12: syntax error: '1 for i in range(5)' came as a comp
lete surprise to me while looking for lexer rule element

**Comment by ericvergnaud** [comment]
the below is not valid antlr code. Your production must go between curly braces.
