### ISSUE TITLE
/usr/bin/python2 cannot be found by default test harness

### ISSUE THREAD

**Issue by sharwell** [antlr/antlr4-python2#54]
The default installation location of Python 2.7 on a fresh Ubuntu installation is `/usr/bin/python2`. This location should be detected and used by the test suite without any additional configuration.

**Comment by ericvergnaud** [comment]
Please feel free to submit a PR for this, I don't have a fresh Ubuntu installation to test against

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4-python2/commit/cfd9641deb00bf3deb290cf32e1bbc9735fbd9d6
